services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: allfactory-backend
    ports:
      - "8002:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE=http://10.1.11.250:8002
    container_name: allfactory-frontend
    ports:
      - "3002:3000"
    depends_on:
      - backend
    restart: unless-stopped